"""
Main Streamlit application for WorkflowAI.
Provides UI for workflow automation using AI agents.
"""

import streamlit as st
import json
import time
import zipfile
import io
from datetime import datetime
from collections import Counter

# Import agents
from agents.workflow_reasoner import WorkflowReasonerAgent
from agents.code_generator import CodeGeneratorAgent
from agents.executor import WorkflowExecutor
from agents.debugger import WorkflowDebuggerAgent
from agents.diagram_generator import DiagramGenerator
from agents.clarifier import ClarifierAgent
from utils.bedrock_client import BedrockClient
from templates import get_all_templates, get_template_descriptions

# Page configuration
st.set_page_config(
    page_title="WorkflowAI - Business Workflow Generator",
    page_icon="🤖",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Example prompts
EXAMPLE_PROMPTS = [
    "Automate employee onboarding with welcome email, Slack account creation, mentor assignment, and meeting scheduling",
    "Create a customer support ticket routing system that categorizes by urgency and assigns to team members",
    "Build an invoice processing workflow that validates amounts, checks approval rules, and updates accounting"
]

# Initialize session state
if 'conversation_history' not in st.session_state:
    st.session_state.conversation_history = []
if 'current_workflow_plan' not in st.session_state:
    st.session_state.current_workflow_plan = None
if 'current_code' not in st.session_state:
    st.session_state.current_code = None
if 'execution_result' not in st.session_state:
    st.session_state.execution_result = None
if 'debugging_history' not in st.session_state:
    st.session_state.debugging_history = []
if 'original_code' not in st.session_state:
    st.session_state.original_code = None
if 'analytics' not in st.session_state:
    st.session_state.analytics = {
        'total_workflows': 0,
        'successful_workflows': 0,
        'total_execution_time': 0.0,
        'workflow_types': []
    }
if 'feedback' not in st.session_state:
    st.session_state.feedback = {}
if 'clarification_mode' not in st.session_state:
    st.session_state.clarification_mode = False
if 'clarification_data' not in st.session_state:
    st.session_state.clarification_data = None
if 'bedrock_client' not in st.session_state:
    try:
        st.session_state.bedrock_client = BedrockClient()
    except Exception as e:
        st.session_state.bedrock_client = None
        st.session_state.bedrock_error = str(e)

def load_template(template_name):
    """Load a pre-built template and populate the text area."""
    if template_name == "Custom":
        return ""
    
    templates = get_all_templates()
    descriptions = get_template_descriptions()
    
    if template_name in templates:
        st.session_state.selected_template = template_name
        st.session_state.template_description = descriptions.get(template_name, "")
        return f"Generate a workflow for: {descriptions.get(template_name, template_name)}"
    return ""

def create_workflow_export(workflow_plan, code):
    """Create a zip file with workflow artifacts."""
    zip_buffer = io.BytesIO()
    
    with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zip_file:
        # Add Python code
        zip_file.writestr('generated_workflow.py', code)
        
        # Add workflow plan JSON
        zip_file.writestr('workflow_plan.json', json.dumps(workflow_plan, indent=2))
        
        # Add README
        readme_content = f"""# {workflow_plan['process_name']}

## Description
{workflow_plan['description']}

## How to Run

1. Ensure Python 3.8+ is installed
2. Run the workflow:
   ```bash
   python generated_workflow.py
   ```

## Workflow Details

- **Complexity**: {workflow_plan['estimated_complexity']}
- **Steps**: {len(workflow_plan['steps'])}
- **Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Required Inputs
{chr(10).join(f'- {inp}' for inp in workflow_plan['inputs'])}

## Expected Outputs
{chr(10).join(f'- {out}' for out in workflow_plan['outputs'])}

## Steps
{chr(10).join(f'{i+1}. {step["step_name"]}: {step["description"]}' for i, step in enumerate(workflow_plan['steps']))}

---
Generated by WorkflowAI - AI-Powered Workflow Generator
"""
        zip_file.writestr('README.txt', readme_content)
    
    zip_buffer.seek(0)
    return zip_buffer

def create_mermaid_diagram(workflow_plan):
    """Create a mermaid flowchart from workflow plan."""
    diagram = "graph TD\n"
    diagram += "    Start([Start]) --> Step1\n"
    
    for i, step in enumerate(workflow_plan['steps'], 1):
        step_id = f"Step{i}"
        next_step_id = f"Step{i+1}" if i < len(workflow_plan['steps']) else "End"
        diagram += f"    {step_id}[{step['step_name']}] --> {next_step_id}\n"
    
    diagram += "    End([Complete])\n"
    return diagram

def update_analytics(workflow_plan, execution_result):
    """Update analytics with workflow results."""
    st.session_state.analytics['total_workflows'] += 1
    
    if execution_result['status'] == 'success':
        st.session_state.analytics['successful_workflows'] += 1
    
    st.session_state.analytics['total_execution_time'] += execution_result.get('execution_time', 0)
    st.session_state.analytics['workflow_types'].append(workflow_plan['process_name'])

def generate_workflow(user_input):
    """Main workflow generation function with enhanced self-debugging."""
    try:
        # Initialize agents
        bedrock_client = st.session_state.bedrock_client
        reasoner = WorkflowReasonerAgent(bedrock_client)
        generator = CodeGeneratorAgent(bedrock_client)
        executor = WorkflowExecutor()
        debugger = WorkflowDebuggerAgent(bedrock_client)
        
        # Step 1: Analyze workflow
        with st.spinner("🧠 Analyzing workflow requirements..."):
            workflow_plan = reasoner.analyze(user_input)
            st.session_state.current_workflow_plan = workflow_plan
            time.sleep(0.5)
        
        st.success("✅ Workflow analysis complete!")
        
        # Step 2: Generate code
        with st.spinner("💻 Generating Python code..."):
            code = generator.generate(workflow_plan)
            st.session_state.current_code = code
            st.session_state.original_code = code  # Save original for comparison
            time.sleep(0.5)
        
        st.success("✅ Code generation complete!")
        
        # Step 3: Execute code
        with st.spinner("⚡ Executing workflow..."):
            execution_result = executor.execute(code)
            st.session_state.execution_result = execution_result
        
        # Step 4: Enhanced self-debugging with retry logic
        max_debug_attempts = 2
        debug_attempt = 0
        
        while execution_result['status'] == 'error' and debug_attempt < max_debug_attempts:
            debug_attempt += 1
            
            # Show error message
            st.warning(f"⚠️ Execution error detected (Attempt {debug_attempt}/{max_debug_attempts})")
            st.error(f"**Error:** {execution_result['error']}")
            
            # Create debugging progress container
            debug_container = st.container()
            
            with debug_container:
                st.markdown("---")
                st.markdown(f"### 🔧 Auto-Debugging (Attempt {debug_attempt})")
                
                # Progress bar
                progress_bar = st.progress(0)
                status_text = st.empty()
                
                # Step 1: Analyze error
                status_text.markdown("🔍 **Analyzing error...**")
                progress_bar.progress(25)
                
                error_analysis = debugger.analyze_error(
                    code,
                    execution_result['error'],
                    workflow_plan
                )
                time.sleep(0.3)
                
                # Display error analysis
                with st.expander("📊 Error Analysis", expanded=True):
                    st.markdown(f"**What went wrong:**")
                    st.info(error_analysis['error_analysis'])
                    st.markdown(f"**Suggested fix:**")
                    st.success(error_analysis['suggested_fix'])
                    st.markdown(f"**Confidence:** {error_analysis['confidence'].upper()}")
                
                # Step 2: Generate fix
                status_text.markdown("🛠️ **Generating fixed code...**")
                progress_bar.progress(50)
                
                fixed_code = debugger.fix_code(code, error_analysis, workflow_plan)
                time.sleep(0.3)
                
                # Show before/after comparison
                status_text.markdown("📝 **Comparing code changes...**")
                progress_bar.progress(75)
                
                with st.expander("🔄 Before vs After Code", expanded=False):
                    col1, col2 = st.columns(2)
                    with col1:
                        st.markdown("**❌ Original (Broken)**")
                        st.code(code[:500] + "..." if len(code) > 500 else code, language="python")
                    with col2:
                        st.markdown("**✅ Fixed**")
                        st.code(fixed_code[:500] + "..." if len(fixed_code) > 500 else fixed_code, language="python")
                
                # Step 3: Re-execute
                status_text.markdown("⚡ **Re-executing fixed workflow...**")
                progress_bar.progress(90)
                
                execution_result = executor.execute(fixed_code)
                st.session_state.execution_result = execution_result
                st.session_state.current_code = fixed_code
                code = fixed_code  # Update for next iteration if needed
                
                progress_bar.progress(100)
                time.sleep(0.3)
                
                # Add to debugging history
                st.session_state.debugging_history.append({
                    'attempt': debug_attempt,
                    'timestamp': datetime.now().isoformat(),
                    'original_error': execution_result.get('error', 'Unknown'),
                    'error_analysis': error_analysis,
                    'fixed_code': fixed_code,
                    'result': execution_result
                })
                
                # Show result
                if execution_result['status'] == 'success':
                    status_text.empty()
                    st.success(f"✅ Self-debugging successful! Workflow fixed and executed (Attempt {debug_attempt})")
                    break
                else:
                    status_text.empty()
                    if debug_attempt < max_debug_attempts:
                        st.warning(f"⚠️ Still has errors. Trying again... (Attempt {debug_attempt + 1}/{max_debug_attempts})")
                    else:
                        st.error(f"❌ Auto-debugging failed after {max_debug_attempts} attempts")
        
        # If still failing after max attempts
        if execution_result['status'] == 'error' and debug_attempt >= max_debug_attempts:
            st.markdown("---")
            st.markdown("### 🛠️ Manual Fix Option")
            st.warning("Auto-debugging couldn't fix the issue. You can try manually editing the code below.")
            
            # Manual code editor
            manual_code = st.text_area(
                "Edit the code:",
                value=st.session_state.current_code,
                height=400,
                key="manual_code_editor"
            )
            
            col1, col2 = st.columns([1, 4])
            with col1:
                if st.button("🔄 Re-run Manual Fix", type="primary"):
                    with st.spinner("⚡ Executing manually fixed code..."):
                        manual_result = executor.execute(manual_code)
                        st.session_state.execution_result = manual_result
                        st.session_state.current_code = manual_code
                        
                        if manual_result['status'] == 'success':
                            st.success("✅ Manual fix successful!")
                        else:
                            st.error(f"❌ Still has errors: {manual_result['error']}")
                        st.rerun()
            
            with col2:
                if st.button("🔄 Try Different Approach"):
                    st.info("💡 Tip: Try simplifying your workflow description or breaking it into smaller steps.")
        
        elif execution_result['status'] == 'success' and debug_attempt == 0:
            st.success("✅ Workflow executed successfully on first try!")
        
        # Add to conversation history
        st.session_state.conversation_history.append({
            'timestamp': datetime.now().isoformat(),
            'input': user_input,
            'workflow_plan': workflow_plan,
            'code': st.session_state.current_code,
            'result': execution_result,
            'debug_attempts': debug_attempt
        })
        
        # Update analytics
        update_analytics(workflow_plan, execution_result)
        
        return True
        
    except Exception as e:
        st.error(f"❌ Error: {str(e)}")
        return False

def main():
    """Main application function."""
    
    # Header
    st.title("🤖 WorkflowAI - AI-Powered Workflow Generator")
    st.markdown("### Convert business processes into production-ready Python code")
    
    # How it works expander
    with st.expander("ℹ️ How It Works", expanded=False):
        st.markdown("""
        **WorkflowAI uses a three-agent AI architecture:**
        
        1. **🧠 Workflow Reasoner** - Analyzes your business requirements and creates a structured plan
        2. **💻 Code Generator** - Converts the plan into clean, executable Python code
        3. **⚡ Executor** - Safely runs the code and captures results
        4. **🔧 Self-Debugger** - Automatically fixes errors if they occur
        
        Simply describe your process in plain English, and WorkflowAI handles the rest!
        """)
    
    # Sidebar
    with st.sidebar:
        st.header("⚙️ Configuration")
        
        # AWS Status
        if st.session_state.bedrock_client:
            st.success("✅ AWS Bedrock Connected")
            st.caption("Using Claude 3.5 Sonnet v2")
        else:
            st.error("❌ AWS Bedrock Not Connected")
            if 'bedrock_error' in st.session_state:
                st.caption(f"Error: {st.session_state.bedrock_error}")
            st.info("""
            **Setup Instructions:**
            1. Configure AWS credentials
            2. Enable Bedrock access
            3. Restart the app
            """)
        
        st.divider()
        
        # Analytics
        st.header("📊 Analytics")
        analytics = st.session_state.analytics
        
        col1, col2 = st.columns(2)
        with col1:
            st.metric("Total", analytics['total_workflows'])
        with col2:
            success_rate = (analytics['successful_workflows'] / analytics['total_workflows'] * 100) if analytics['total_workflows'] > 0 else 0
            st.metric("Success", f"{success_rate:.0f}%")
        
        if analytics['total_workflows'] > 0:
            avg_time = analytics['total_execution_time'] / analytics['total_workflows']
            st.metric("Avg Time", f"{avg_time:.2f}s")
            
            # Most common workflow types
            if analytics['workflow_types']:
                workflow_counts = Counter(analytics['workflow_types'])
                most_common = workflow_counts.most_common(1)[0]
                st.caption(f"Most common: {most_common[0][:20]}...")
        
        st.divider()
        
        # About section
        st.header("📖 About")
        st.markdown("""
        **Three AI Agents:**
        - 🧠 Workflow Reasoner
        - 💻 Code Generator  
        - 🔧 Self-Debugger
        
        **Features:**
        - Natural language input
        - Automatic code generation
        - Safe execution
        - Self-debugging
        """)
        
        st.divider()
        
        # Template selector
        st.header("📋 Templates")
        template_options = ["Custom"] + list(get_template_descriptions().keys())
        selected_template = st.selectbox(
            "Choose a template:",
            template_options,
            help="Select a pre-built template or create custom workflow"
        )
        
        if selected_template != "Custom":
            descriptions = get_template_descriptions()
            st.info(descriptions.get(selected_template, ""))
        
        st.divider()
        
        # Clear history
        if st.button("🗑️ Clear History", use_container_width=True):
            st.session_state.conversation_history = []
            st.session_state.current_workflow_plan = None
            st.session_state.current_code = None
            st.session_state.execution_result = None
            st.session_state.debugging_history = []
            st.session_state.original_code = None
            st.rerun()
    
    # Main content area
    st.divider()
    
    # Help section
    with st.expander("❓ Help & Tips", expanded=False):
        st.markdown("""
        ### How to Write Effective Prompts
        
        **Be Specific:**
        - ✅ "Send welcome email to new employee with start date and team info"
        - ❌ "Send email"
        
        **List Steps:**
        - Break down your process into clear steps
        - Mention the order of operations
        - Include conditions (if/then)
        
        **Mention Integrations:**
        - Specify tools: "Send Slack message", "Update database", "Create calendar event"
        - Name systems: "Salesforce", "Gmail", "Jira"
        
        ### What Makes a Good Workflow
        
        **Ideal Complexity:**
        - 3-10 steps works best
        - Each step should be clear and actionable
        - Avoid overly complex logic
        
        **Good Examples:**
        - Employee onboarding automation
        - Support ticket routing
        - Invoice approval process
        - Report generation and distribution
        
        ### Troubleshooting
        
        **If code fails:**
        - Our self-debugger will automatically fix most errors
        - Try simplifying your workflow description
        - Break complex workflows into smaller parts
        
        **AWS Setup:**
        1. Configure credentials: `aws configure`
        2. Enable Bedrock in AWS Console
        3. Request Claude 3.5 Sonnet access
        4. Restart the app
        """)
    
    # Input section
    st.header("📝 Describe Your Workflow")
    
    # Example prompts as buttons
    st.markdown("**Quick Examples:**")
    cols = st.columns(3)
    for idx, example in enumerate(EXAMPLE_PROMPTS):
        with cols[idx]:
            if st.button(f"Example {idx+1}", use_container_width=True, help=example):
                st.session_state.user_input = example
                st.rerun()
    
    # Load template if selected
    default_input = ""
    if selected_template != "Custom":
        default_input = load_template(selected_template)
    
    # Text area for input
    user_input = st.text_area(
        "Describe your business process:",
        value=st.session_state.get('user_input', default_input),
        height=150,
        placeholder="Example: I need to automate employee onboarding - send welcome email, create Slack account, assign mentor, and schedule first week meetings",
        help="Describe your workflow in plain English. Be specific about the steps you want to automate."
    )
    
    # Character counter
    char_count = len(user_input)
    st.caption(f"Characters: {char_count} | Words: {len(user_input.split())}")
    
    # Generate button
    col1, col2, col3 = st.columns([2, 1, 2])
    with col2:
        generate_button = st.button(
            "🚀 Generate Workflow",
            type="primary",
            disabled=not user_input.strip() or not st.session_state.bedrock_client,
            use_container_width=True
        )
    
    # Process workflow generation
    if generate_button:
        # Check if clarification needed
        clarifier = ClarifierAgent(st.session_state.bedrock_client)
        
        with st.spinner("🤔 Analyzing requirements..."):
            clarification = clarifier.analyze_requirements(user_input)
        
        if clarification['needs_clarification'] and clarification['confidence'] < 80:
            st.session_state.clarification_mode = True
            st.session_state.clarification_data = {
                'original_input': user_input,
                'clarification': clarification
            }
            st.rerun()
        else:
            st.divider()
            st.header("🔄 Processing...")
            success = generate_workflow(user_input)
            
            if success:
                st.balloons()
    
    # Clarification mode
    if st.session_state.clarification_mode and st.session_state.clarification_data:
        st.divider()
        st.info("🤔 I need a bit more information to build the perfect workflow:")
        
        clarification = st.session_state.clarification_data['clarification']
        original_input = st.session_state.clarification_data['original_input']
        
        # Show ambiguities
        if clarification.get('ambiguities'):
            with st.expander("⚠️ What's unclear", expanded=False):
                for amb in clarification['ambiguities']:
                    st.markdown(f"- {amb}")
        
        # Ask questions
        answers = []
        for i, question in enumerate(clarification['questions'][:3]):
            answer = st.text_input(f"Q{i+1}: {question}", key=f"clarify_q_{i}")
            answers.append(answer)
        
        col1, col2 = st.columns([1, 4])
        with col1:
            if st.button("✅ Submit Answers", type="primary", disabled=not all(answers)):
                with st.spinner("📝 Refining requirements..."):
                    clarifier = ClarifierAgent(st.session_state.bedrock_client)
                    enhanced_input = clarifier.refine_requirements(
                        original_input,
                        clarification['questions'],
                        answers
                    )
                
                st.success("✅ Got it! Generating enhanced workflow...")
                st.session_state.clarification_mode = False
                st.session_state.clarification_data = None
                
                st.divider()
                st.header("🔄 Processing...")
                success = generate_workflow(enhanced_input)
                
                if success:
                    st.balloons()
        
        with col2:
            if st.button("⏩ Skip Clarification"):
                st.session_state.clarification_mode = False
                st.session_state.clarification_data = None
                
                st.divider()
                st.header("🔄 Processing...")
                success = generate_workflow(original_input)
                
                if success:
                    st.balloons()
    
    # Results section
    if st.session_state.current_workflow_plan:
        st.divider()
        st.header("📊 Results")
        
        tab1, tab2, tab3, tab4, tab5 = st.tabs(["📋 Workflow Plan", "💻 Generated Code", "📊 Diagram", "⚡ Execution Results", "📅 History"])
        
        # Tab 1: Workflow Plan
        with tab1:
            plan = st.session_state.current_workflow_plan
            
            col1, col2 = st.columns([2, 1])
            with col1:
                st.subheader(plan['process_name'])
                st.markdown(f"**Description:** {plan['description']}")
            with col2:
                complexity_color = {
                    'low': '🟢',
                    'medium': '🟡',
                    'high': '🔴'
                }
                st.metric(
                    "Complexity",
                    plan['estimated_complexity'].upper(),
                    delta=None
                )
            
            st.markdown("---")
            
            # Steps
            st.markdown("**Workflow Steps:**")
            for step in plan['steps']:
                with st.expander(f"Step {step['step_number']}: {step['step_name']}", expanded=True):
                    st.markdown(f"**Description:** {step['description']}")
                    st.markdown(f"**Action:** `{step['action']}`")
                    if step.get('integration_needed'):
                        st.markdown(f"**Integration:** {step['integration_needed']}")
            
            # Inputs and Outputs
            col1, col2 = st.columns(2)
            with col1:
                st.markdown("**Required Inputs:**")
                for inp in plan['inputs']:
                    st.markdown(f"- {inp}")
            with col2:
                st.markdown("**Expected Outputs:**")
                for out in plan['outputs']:
                    st.markdown(f"- {out}")
            
            # JSON view
            with st.expander("📄 View Full JSON"):
                st.json(plan)
            
            # Mermaid diagram
            with st.expander("📊 Workflow Visualization", expanded=False):
                mermaid_code = create_mermaid_diagram(plan)
                st.code(mermaid_code, language="mermaid")
                st.caption("Copy this code to visualize at mermaid.live")
        
        # Tab 2: Generated Code
        with tab2:
            if st.session_state.current_code:
                st.markdown("**Generated Python Code:**")
                
                # Action buttons
                col1, col2, col3 = st.columns([1, 1, 3])
                with col1:
                    if st.download_button(
                        "📥 Download",
                        st.session_state.current_code,
                        file_name=f"workflow_{datetime.now().strftime('%Y%m%d_%H%M%S')}.py",
                        mime="text/plain",
                        use_container_width=True
                    ):
                        st.success("Code downloaded!")
                
                with col2:
                    # Export workflow as zip
                    if st.session_state.current_workflow_plan:
                        zip_file = create_workflow_export(
                            st.session_state.current_workflow_plan,
                            st.session_state.current_code
                        )
                        st.download_button(
                            "📦 Export All",
                            zip_file,
                            file_name=f"workflow_export_{datetime.now().strftime('%Y%m%d_%H%M%S')}.zip",
                            mime="application/zip",
                            use_container_width=True,
                            help="Download code, plan, and README as zip"
                        )
                
                # Code display
                st.code(st.session_state.current_code, language="python", line_numbers=True)
                
                # Feedback buttons
                st.markdown("---")
                st.markdown("**Was this workflow helpful?**")
                col1, col2, col3 = st.columns([1, 1, 4])
                
                workflow_id = st.session_state.conversation_history[-1]['timestamp'] if st.session_state.conversation_history else 'current'
                
                with col1:
                    if st.button("👍 Helpful", key=f"thumbs_up_{workflow_id}"):
                        st.session_state.feedback[workflow_id] = 'positive'
                        st.success("Thanks for your feedback!")
                
                with col2:
                    if st.button("👎 Not Helpful", key=f"thumbs_down_{workflow_id}"):
                        st.session_state.feedback[workflow_id] = 'negative'
                        st.info("Thanks! We'll improve.")
            else:
                st.info("No code generated yet.")
        
        # Tab 3: Diagram
        with tab3:
            st.subheader("Visual Workflow")
            
            # Generate diagram
            diagram_gen = DiagramGenerator()
            mermaid_code = diagram_gen.generate_mermaid(st.session_state.current_workflow_plan)
            
            # Display diagram
            st.markdown("```mermaid\n" + mermaid_code + "\n```")
            
            # Download options
            col1, col2 = st.columns([1, 4])
            with col1:
                st.download_button(
                    "📥 Download",
                    mermaid_code,
                    file_name=f"workflow_diagram_{datetime.now().strftime('%Y%m%d_%H%M%S')}.mmd",
                    mime="text/plain",
                    use_container_width=True
                )
            
            st.caption("💡 Copy the code above to visualize at [mermaid.live](https://mermaid.live)")
        
        # Tab 4: Execution Results
        with tab4:
            if st.session_state.execution_result:
                result = st.session_state.execution_result
                
                # Status header with visual indicators
                if result['status'] == 'success':
                    if st.session_state.debugging_history:
                        st.success(f"✅ 🔧 Fixed after debugging (took {result['execution_time']}s)")
                    else:
                        st.success(f"✅ Execution Successful (took {result['execution_time']}s)")
                else:
                    st.error(f"❌ Execution Failed (took {result['execution_time']}s)")
                
                # Debugging History Section
                if st.session_state.debugging_history:
                    with st.expander("🔧 Debugging History", expanded=True):
                        st.markdown("### Self-Debugging Process")
                        
                        for idx, debug_entry in enumerate(st.session_state.debugging_history):
                            st.markdown(f"---")
                            st.markdown(f"#### Attempt {debug_entry['attempt']}")
                            
                            # Timeline visualization
                            col1, col2, col3, col4 = st.columns(4)
                            
                            with col1:
                                st.markdown("🔴 **Error Detected**")
                                st.caption(debug_entry.get('original_error', 'Unknown')[:50] + "...")
                            
                            with col2:
                                st.markdown("🔵 **Analyzed**")
                                analysis = debug_entry.get('error_analysis', {})
                                st.caption(f"Confidence: {analysis.get('confidence', 'N/A').upper()}")
                            
                            with col3:
                                st.markdown("🟡 **Fixed**")
                                st.caption("Code regenerated")
                            
                            with col4:
                                status = debug_entry.get('result', {}).get('status', 'unknown')
                                if status == 'success':
                                    st.markdown("🟢 **Success**")
                                    st.caption("✅ Executed")
                                else:
                                    st.markdown("🔴 **Failed**")
                                    st.caption("❌ Still errors")
                            
                            # Detailed analysis
                            with st.expander(f"View Details - Attempt {debug_entry['attempt']}"):
                                st.markdown("**Error Analysis:**")
                                st.info(analysis.get('error_analysis', 'N/A'))
                                st.markdown("**Suggested Fix:**")
                                st.success(analysis.get('suggested_fix', 'N/A'))
                
                # Output
                st.markdown("---")
                st.markdown("**Execution Output:**")
                if result['output']:
                    st.text_area(
                        "Console Output",
                        result['output'],
                        height=300,
                        disabled=True
                    )
                else:
                    st.info("No output captured.")
                
                # Error details
                if result['error']:
                    st.markdown("**Error Details:**")
                    st.error(result['error'])
            else:
                st.info("No execution results yet. Generate a workflow first.")
        
        # Tab 5: History
        with tab5:
            if st.session_state.conversation_history:
                st.markdown("### Recent Workflows")
                st.caption(f"Showing last {min(5, len(st.session_state.conversation_history))} workflows")
                
                # Show last 5 workflows
                recent_workflows = st.session_state.conversation_history[-5:]
                recent_workflows.reverse()  # Most recent first
                
                for idx, workflow in enumerate(recent_workflows):
                    with st.expander(
                        f"{workflow['workflow_plan']['process_name']} - {datetime.fromisoformat(workflow['timestamp']).strftime('%Y-%m-%d %H:%M')}",
                        expanded=False
                    ):
                        col1, col2, col3 = st.columns(3)
                        
                        with col1:
                            status = workflow['result']['status']
                            status_icon = "✅" if status == 'success' else "❌"
                            st.metric("Status", f"{status_icon} {status.upper()}")
                        
                        with col2:
                            exec_time = workflow['result'].get('execution_time', 0)
                            st.metric("Execution Time", f"{exec_time}s")
                        
                        with col3:
                            debug_attempts = workflow.get('debug_attempts', 0)
                            st.metric("Debug Attempts", debug_attempts)
                        
                        st.markdown("**User Input:**")
                        st.text(workflow['input'][:200] + "..." if len(workflow['input']) > 200 else workflow['input'])
                        
                        # Reload button
                        if st.button(f"🔄 Reload This Workflow", key=f"reload_{idx}"):
                            st.session_state.current_workflow_plan = workflow['workflow_plan']
                            st.session_state.current_code = workflow['code']
                            st.session_state.execution_result = workflow['result']
                            st.success("Workflow reloaded!")
                            st.rerun()
                
                # Feedback stats
                if st.session_state.feedback:
                    st.markdown("---")
                    st.markdown("### Feedback Summary")
                    positive = sum(1 for f in st.session_state.feedback.values() if f == 'positive')
                    negative = sum(1 for f in st.session_state.feedback.values() if f == 'negative')
                    total = positive + negative
                    
                    if total > 0:
                        col1, col2, col3 = st.columns(3)
                        with col1:
                            st.metric("👍 Positive", positive)
                        with col2:
                            st.metric("👎 Negative", negative)
                        with col3:
                            satisfaction = (positive / total * 100) if total > 0 else 0
                            st.metric("Satisfaction", f"{satisfaction:.0f}%")
            else:
                st.info("No workflow history yet. Generate your first workflow to get started!")
    
    # Footer
    st.divider()
    st.caption("Built with AWS Bedrock Claude 3.5 Sonnet | Powered by Multi-Agent AI Architecture")

if __name__ == "__main__":
    main()
